version: "3"
services:
  nginx:
    image: nginx:stable
    ports:
      - "8088:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

#  app:
#    build: ./app
#    volumes:
#      - ./app:/app
#    network_mode: host

